-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1114150
-- Generated: 2026-09-08T19:43:33.443Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1114150)
addappid(1114151,0,"472bd3a70105d0685574189912e9cf277940a72c562a19db7509fc56da74f3de")
setManifestid(1114151,"5884140393804545570")