-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1190000
-- Generated: 2026-09-08T22:29:15.920Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1190000)
setManifestid(228990,"1829726630299308803")
addappid(1190001,0,"b4f04348a15ca7c50e5275db9f0569947a2e3926ad0f05db23b4032050ee2f77")
setManifestid(1190001,"2275966675234962197")