-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1211020
-- Generated: 2026-09-11T00:03:58.328Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1211020, 1, "4466a73b43a075c4ca3b00241dd9675d13d06fa9329c8bb755d450a683d1f833") 
addappid(1211023, 1, "7b55e9caab84de4a05399572557f58ecac6abd4d5b31564b0d5356ac6e79807b") 
setManifestid(1211023, "7435321304148525401", 1624066288)