-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1222140
-- Generated: 2026-09-09T07:30:41.253Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1222140, 1, "c86eb22d1ee19339760143055ce73a32b48e96f7dbd06d56db43b97a5fea5f30") 
addappid(1222141, 1, "d87af32872df297ec519d0e79b6e0afc327b09048c3414622606b54efc46f519") 
setManifestid(1222141, "7324084008489949045", 54953473904)