-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1229490
-- Generated: 2026-09-08T23:07:07.421Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1229490)
addappid(1229491,0,"347634f48592b176da96c10b8afe6898527aa5c218d89930f9d6e5b6d5e7c8ba")
setManifestid(1229491,"6093621263526928435")