-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1331550
-- Generated: 2026-09-11T04:14:55.249Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1331550, 1, "159ee5940ca12f8daef8eccc0d528f6dff71e38da7b5d9fec465ed4fdd63e401") 
addappid(1331551, 1, "f3b44da48f4335a1dad963250d348f21e38cb27fbe8264e2cd0ebf217849a089") 
setManifestid(1331551, "7001139920346164058", 3095729088)
addappid(1331552, 1, "1547279019dc793ecffc735c9690f060ed6a8c2fd0145e1e4c605b795cc423d9") 
setManifestid(1331552, "8124138447764310195", 2947319664)