-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1454400
-- Generated: 2026-09-11T22:38:25.172Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1454400, 1, "bee35fc41b9a4f44f4d1017924dcc20a9241b2755b02a3178baee78dc2f49ab9") 
addappid(1454401, 1, "dc8be6e8bb8cf9a7d3f548fe759eb532def1c3d380deece391d81dafa6c96e67") 
setManifestid(1454401, "5817090063491018460", 100900736)
addappid(1454402, 1, "39c00dfd8ff729f8012400b55fc6d55b1c21b5ee2b012fe72a6c33b5b5ec176b") 
setManifestid(1454402, "1124352571317316090", 156932720)

addappid(1738020) 
addappid(1738021, 1, "2ce0503c73a5d7d5e684ef6cca5a7e125b56eff799567a59cf4a247455bd7e13") 
setManifestid(1738021, "9201460407362736022", 32104784)
addappid(1738022, 1, "49267d0594a11ffd07cc226d84890c7826b85fa55622b99f20fa40f4d09ba94a") 
setManifestid(1738022, "4611986400370368504", 113821264)