-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1494840
-- Generated: 2026-09-08T20:38:52.997Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1494840)
addappid(1494841,0,"eb14283ecc75934fce88f8dc7b3eeeee8e138990a7befcdcc3b80a618755a353")
setManifestid(1494841,"6299956753621727440")