-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1527950
-- Generated: 2026-09-09T07:27:20.615Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1527950, 1, "df3fb79e39a23369ab2a734aa3168b065638b173cb7cc3842a16f676adbfbeee") 
addappid(1527951, 1, "95bd24e7b06dd6b363b41cd5735569fe66f9d030ec1b11d30e46c13171a17852") 
setManifestid(1527951, "4350244590885432578", 16270280720)

addappid(3533110) 
addappid(3533111, 1, "3354e8e7365b10273c0c78b9cd7518719e8363fd3a2b09af934059b80307d624") 
setManifestid(3533111, "1590043208140971743", 113068064)
addappid(3533112, 1, "ac370f744d81811d0f2349a8f98ddbaa19edad8c1d9771965373b165c78db5aa") 
setManifestid(3533112, "1840744157618419814", 1756218592)

addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") 
setManifestid(228988, "6645201662696499616", 22411856)
addappid(2692400) 
addappid(2903960) 
addappid(3112270) 
addappid(3335020) 
addappid(3559560) 
addappid(3899740) 
addappid(4165520) 
addappid(4490120) 