-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1578390
-- Generated: 2026-09-11T11:21:41.412Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1578390, 1, "357c6adb28c794eaab399c050482a1f6018db2109096614e36a65985076ce3ba") 
addappid(1578391, 1, "2629060dc735b648e02216c3c27486fc1158eabb37d690a8d820d7565abe107f") 
setManifestid(1578391, "76355034690939128", 5523649312)