-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1592190
-- Generated: 2026-09-10T19:28:27.581Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1592190, 1, "b57d7fa630008f2ce8154a106d6746fd00094819aa53a14aae15d2d299dda4ad") 
addappid(1592191, 1, "bc35259e671ec631d2c638538cb2cabeb1201419b767484986fd0c9145ca0713") 
setManifestid(1592191, "5849268138679869641", 10140937296)