-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1593500
-- Generated: 2026-09-12T11:29:00.912Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1593500, 1, "93b91503fb7aaf54f61ae3197cf1790f9889d142399e30f9bd439e7c6a7dc9f8") 
addappid(1593501, 1, "77f7390a115063bccc41240f71e0bf27d42c6a7c0424657756fe3f99f26a287a") 
setManifestid(1593501, "2535153423663269664", 37134232112)

addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") 
setManifestid(228988, "6645201662696499616", 22411856)