-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1648533
-- Generated: 2026-09-09T10:54:05.113Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1648533, 0, "bbbe556130b14da3a5ca411554fb6c78bbf260b077826feef1a3b74ed35f2734")