-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1671210
-- Generated: 2026-09-12T06:36:40.399Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1671210, 1, "6629fad6c9567402765959ebaa51e3dbf2b29f1d250f1c8bc7a757d1afcc96fe") 
addappid(1671212, 1, "d3b68663ee177c37ee1d5cb49de06cbf9d0d81b2b72ffdde18665f6db6c6ed9f") 
setManifestid(1671212, "2054633419585385858", 579341344)
addappid(1671213, 1, "06e8fc629b33851989bebbd53c9e8acde2444b4c75fbf43036e586cc4bc6b1a5") 
setManifestid(1671213, "4660325583654611134", 581461104)

addappid(3752270) 
addappid(3752271, 1, "352d2c9e8397db32f09c71c78630d3e0757d88c64a5b3cdc90ff9c5e8d4e29d3") 
setManifestid(3752271, "7122322280114860774", 600322480)
addappid(3752272, 1, "c062539fd525e69dac6f63b0affb372c2786b5ada1dced6d177bc1959b859f11") 
setManifestid(3752272, "7849333747937066100", 2450531952)