-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1702390
-- Generated: 2026-09-09T00:43:27.410Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1702390)
setManifestid(228988,"6645201662696499616")
setManifestid(228990,"1829726630299308803")
addappid(1702391,0,"681e40088f726437f9224623495d73305f41d9023d688b6956c352b2d5a9b759")
setManifestid(1702391,"1067469324919812731")