-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1787090
-- Generated: 2026-09-11T16:50:52.419Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1787090, 1, "b73aacc1923ae6095b2b9a1892738fa98c1ef57355894e41ac8414b3070fd208") 
addappid(1787091, 1, "89e81a11a8a9323dc60060cb60eb73aea9b74b25d1c2a40f1bc86e5c67339b06") 
setManifestid(1787091, "2270585393664965838", 120926880)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(229007, 1, "eba9fa9ff4f811929c119074450f49f739113bcae9317ded9bea262aa21ec58d") 
setManifestid(229007, "4477590687906973371", 118846656)