-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1817490
-- Generated: 2026-09-11T20:38:36.436Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1817490, 1, "573394a981afdead7fe72fa4c94f5021c55e70f1f5aea37a1f15af5d2bcae9c5") 
addappid(1817491, 1, "e8a0b69343b9b3297a7db08e084898fd14130435cf9b95a9e77b794a430e66a0") 
setManifestid(1817491, "2957411760343078601", 8698128896)