-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1826420
-- Generated: 2026-09-08T18:02:44.019Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1826420) 
addappid(1826421, 1, "19944d24b1486ec368bb854981e194f1c8020658e793d499778efefb5e9c7443") 
setManifestid(1826421, "5945870121530017294", 16346188096)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)