-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1874880
-- Generated: 2026-09-08T22:34:07.936Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1874880)
setManifestid(228989,"3514306556860204959")
addappid(1874881,0,"f1bc308d3a58a8d144a76dc02d552819b433bda49c325060fcab53e8100cead3")
setManifestid(1874881,"3208659220235311754")
addappid(1874882,0,"c964efe3e6ee7295beeb474f46e6c78d1f2f62097dc3c793b1474cfab9f2f055")
setManifestid(1874882,"1650233779375073015")