-- 1888930's Lua and Manifest Generated by Morrenus
-- The Last of Us™ Part I
-- Generated: 2025-09-27 04:34:57
-- Total Depots: 4
-- Total DLCs: 2
-- Shared Depots: 1

-- MAIN APPLICATION
addappid(1888930) -- The Last of Us™ Part I
-- MAIN APP DEPOTS
addappid(1888931, 1, "19cd197b4bc7e62551196ec84d00da135a4dedeb5edca50804001bf9e90b6b70") -- Depot 1888931
setManifestid(1888931, "4945188123625783686", 68213988274)
addappid(1888933, 1, "035887e659bc052ab1d1801d1665304be7da49992076cd123e25b9bd06a64134") -- Depot 1888933
setManifestid(1888933, "7178411350218387234", 3197773819)
addappid(1888932, 1, "20a675f9d2a0efd0cf0f8985b2a1c67d5d64e1c2b5aee665d3692969b28b1be4") -- Depot 1888932
setManifestid(1888932, "5557770133008488072", 16291650422)
-- SHARED DEPOTS (from other apps)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- VC 2019 Redist (Shared from App 228980)
setManifestid(228988, "6645201662696499616", 29212173)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(2245260) -- The Last of Us Part I - Pre-purchase Entitlements
addappid(2254450) -- The Last of Us Part I - Upgrade to Digital Deluxe Edition