-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1899060
-- Generated: 2026-09-11T18:51:48.828Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(1899060) 
addappid(1899061, 1, "030c9f637fe11abc1a8a13a6b1914824121f11b52e3fc7cfd134b372a6fc8bd4") 
setManifestid(1899061, "7080465818036104893", 1908247216)
addappid(1899063, 1, "83c1d30b6ad29af0986517a00158d83fcd9307bc36d722292a428865b61778c1") 
setManifestid(1899063, "4381734179313484424", 2079307744)

addappid(2399050) 
addappid(2399051, 1, "dbf200cfe517bf9a2a9599ff506f285a83fdb2461306ca3fd8c6182dfb6a143c") 
setManifestid(2399051, "6874521947070688540", 429180800)
addappid(2399052, 1, "99fd3976dcd018168c751252cfaeb7c1dddd4ccc83d2a6a4a2b32f2de228ebbf") 
setManifestid(2399052, "5499773154157858055", 944308320)