-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1914060
-- Generated: 2026-09-09T00:19:26.610Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1914060)
addappid(1914061,0,"61f0d4c2ad5f5b7d8919793bf3610b4629292d8ec7e72c6fb9d62cf7f8672ffd")
setManifestid(1914061,"6680818942387521020")