-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 1943950
-- Generated: 2026-09-08T20:13:17.930Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: manifestHub

addappid(1943950)
setManifestid(228989,"3514306556860204959")
setManifestid(228990,"1829726630299308803")
addappid(1943951,0,"7930e28c405ca5c1ab83cb57ad8f6a96adc288960b0e60acbc764ff1154d8bb3")
setManifestid(1943951,"4105378663961580580")