-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(1989120, 1, "0dffd34524bbc6f26430ebb8be22c87fd90d83b210158d5799fba232fcbcbcf7")
addappid(1989121, 1, "b953bbbed95b1e6ed9b29a6adc9166814ce26f234b488070187e4dfadadbfead")
setManifestid(1989121, "7999966746734539189", 1418094224)
addappid(4484170)
addappid(4484170, 1, "35dc4cfba401dc8d712a28292da6d7231a41632c7b90fce0a6f13147e1f3f5fd")
setManifestid(4484170, "5665791319036157048", 38052977)
