-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 2126550
-- Generated: 2026-09-08T17:25:52.462Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(2126550) 
addtoken(2126550, "7076003629073762327")
addappid(2126551, 1, "d3da5868018b14337e64d25017c5ff5cb59dd2b64d9ef403fbc5e2471abe60a8") 