-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(2148060)
addappid(2148061, 1, "f002bfc2e6ffd4b19e232812acf35a7f2544c9967cdae90ef2f418dd81550670")
setManifestid(2148061, "5201642007624352122", 179258220)
addappid(2162000)
addappid(2169190)
addappid(2169210)
addappid(2169280)
