-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 2183750
-- Generated: 2026-09-11T16:23:15.398Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(2183750) 
addappid(2183751, 1, "07d4faa0aa258455d9140e165f3463656cfc4ba41c8ff91eb2bef721881cf049") 
setManifestid(2183751, "168203355541249835", 64)