-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 2327720
-- Generated: 2026-09-11T20:11:30.773Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(2327720, 1, "698557f3ecf2f050f00b7fcf1c0ce9f89425e8a62dd2d2f932b694f3b622ae7f") 
addappid(2327721, 1, "e7f5c17d4db7edb932a65bef69f5d9dcf9f6519ce55c9cc89520deaa8024bc65") 
setManifestid(2327721, "2706099533555491071", 11929126704)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)