-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 2406770
-- Generated: 2026-09-12T05:49:11.258Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(2406770, 1, "70969ed45a39a813850ed9d81a50af9aabc5fc4ebd8fc1216ed260e04487cb50") 
addappid(2406771, 1, "0456324ba6c023dafc26bedc6005e6145a7b03bfe59a6d2806bf7e07ef54e6c2") 
setManifestid(2406771, "5191741311888999039", 53237762288)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)