-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 2479810
-- Generated: 2026-09-10T23:21:37.174Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(2479810, 1, "49ada9d51358b95a5416b3f17c6c2ead1b8171c2fe362c9266ed1489ce6a0576") 
addappid(2479811, 1, "c89db92b0e186d8c1e9db781270fc739b23f152b3e11ed7733f93bba19ce6716") 
setManifestid(2479811, "1773837463786738408", 20415624368)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)
addappid(2633470) 
addappid(2914230) 
addappid(2955580) 