-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(2578960)
addappid(2578961, 1, "7fcd68aefa53b64a615bb154cf10ad7e801da928e44d6d3a6b115010e34940b9")
setManifestid(2578961, "6853623781670262329", 11121927703)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853")
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8")
setManifestid(228990, "1829726630299308803", 102931551)
addappid(229000, 1, "3aae9271fb93da5395ffbfe338d3647de5dcfab3fc6fb901ca2ec28849b3d6bf")
setManifestid(229000, "4622705914179893434", 242743889)
