-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 2692400
-- Generated: 2026-09-09T07:37:00.688Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(2692400, 0, "eb509ffc91af085e7fd548c62a673a840bfaaaf550fc35ea3cccfdbab7d153a5")