-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 2710480
-- Generated: 2026-09-09T04:06:57.815Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(2710480, 1, "6021f76c5d3db206a898fe4abf64eead00ec420eb17bbb22deb76c9bbc9b75e6") 
addappid(2710481, 1, "7765451235157fe8932eeebf00a41af0f17b2267a35e3795492dd9b7b3931572") 
setManifestid(2710481, "5762499936092396568", 12054611904)