-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3167920
-- Generated: 2026-09-11T20:44:32.060Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3167920, 1, "1cc070798c547c218ca5b280a7ec44c479839c6c2bbc7bcdfb1e96b0cf17c99a") 
addappid(3167921, 1, "1ed77059aee14eb6bb4872955ca84a0ae7880ce352cbfffefbbd91eca2e98006") 
setManifestid(3167921, "4783820022033533712", 13783449168)

addappid(4948230, 1, "8d0687c48e6b694c4e272f79155968c895660a6295ecee04387f52316b384c66") 
setManifestid(4948230, "2163324108419107986", 62797168)

