-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3233230
-- Generated: 2026-09-10T02:18:57.269Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3233230) 
addappid(3233231, 1, "6d0a9b03393128ffc79968c19bb6aaa256a6f855439b64c017b8eed89d9b4855") 
setManifestid(3233231, "505477669639574228", 2619289456)