-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(3306180)
addappid(3306181, 1, "c14ffb6563c349e7def819496c207bd190777e8e2c3aed59be5ab8ec2099c092")
setManifestid(3306181, "9033624331640841121", 4326514115)
addappid(3306182, 1, "aabac9b62935af8f1750348c2ba0e7c985f65bcd68fcf4d564bcf173a3cafdae")
setManifestid(3306182, "5482116265750058745", 4345927197)
