-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3335020
-- Generated: 2026-09-09T07:34:19.299Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3335020, 0, "4135561c0b3efae938863cdf963af27d5f84819824422023289aa0865cbbdd70")