-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3455410
-- Generated: 2026-09-12T13:53:43.950Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3455410) 
addappid(3455411, 1, "7e87fc79ed27aac59a27741aef81c2f89ffddb5ea72f09dc1bba09cac51a26b6") 
setManifestid(3455411, "4856113273222537180", 6755864976)

addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") 
setManifestid(228988, "6645201662696499616", 22411856)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)