-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3474900
-- Generated: 2026-09-12T13:49:14.044Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3474900, 1, "6962e235f2435a469ecb60cd81380e00dc587a5d3bcb7d7090db101661c4990b") 
addappid(3474901, 1, "fbc9891a1c20a2a57931cc7ac38cec562cf9fb996f284e99863b13fb98f140d8") 
setManifestid(3474901, "3253178338511696472", 860810256)