-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3527290
-- Generated: 2026-09-12T06:48:51.535Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3527290, 1, "499eb049b24a30730d5926e9cf72bfa9237d1a7f6de06e94a05e9c2c01348478") 
addappid(3527291, 1, "f55585bb6a00ba332421256f80ba05e27afc38fec6170b9a763138244c506f05") 
setManifestid(3527291, "269859723287817937", 1559371008)