-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3559560
-- Generated: 2026-09-09T07:33:25.345Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3559560, 0, "f74d6550742f86087969b6f3db75275e789dc1871cfddd386defdb3011f198d4")