-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(3578460)
addappid(3578461, 1, "a5b1dffd7b86d05ee6d3ace4a9c1beb1d3f3e0f3299ad96e316fc7df04774c5b")
setManifestid(3578461, "3551986525621596705", 8201766389)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853")
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8")
setManifestid(228990, "1829726630299308803", 102931551)
