-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3689660
-- Generated: 2026-09-11T01:03:58.750Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3689660) 
addappid(3689661, 1, "2154312922e19aa77b3bced674aa1548a737b74f7b1e9c3a522e92fee80e0338") 
setManifestid(3689661, "2734589505434151735", 1354902784)