-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(3700130, 1, "5333441d13d2ecc4ec6fc85e6ceb45b11d6ab10e0f9d420cb87179b23625d8cd")
addappid(3700131, 1, "c216c4808be5c077a6600c83b0f681fd08a7d3b43b6eecdfbd01a6064c79ac74")
setManifestid(3700131, "7261862980337672772", 916631327)
addappid(4726860)
addappid(4726860, 1, "47059ae5fea358c331b5806818b8c8d941b6c25927609ad6ed5248f830ff8dff")
setManifestid(4726860, "3246367678752513925", 63725464)
