-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 370240
-- Generated: 2026-09-09T07:55:10.711Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(370240) 
addappid(370241, 1, "2834e0599f82797bd1af42488a12abeb892bd2d3e9a8ce684fd601e6e56c1cab") 
setManifestid(370241, "476087243588707670", 47350537600)

addappid(228984, 1, "df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") 
setManifestid(228984, "2547553897526095397", 13436144)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)
addappid(386720) 
addappid(386721) 
addappid(486710) 