-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(3710840)
addappid(3710841, 1, "488fc8ff042da5fbec1bbf2ace38baed5d94b2ca030a4d5da53c90366e489bc4")
setManifestid(3710841, "5063346441494313414", 28705781004)
addappid(3710842, 1, "4ac9eb8ffd1dbaf7f1e0854c65fbee712878183417b817be2a5ddea9133910aa")
setManifestid(3710842, "3340507047888663151", 54332157202)
