-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(3807250)
addappid(3807251, 1, "b54e181c5ea54c4cd1421dfbc9b9b575b2abb989740dce9e6b6ab32f42fa6e97")
setManifestid(3807251, "4051161200407459321", 273369432)
addappid(3807252, 1, "6a424b8bd3c43143a2c5e26ec83e7e4267d37f48dd8b6c0d4d55da7e6cabc0eb")
setManifestid(3807252, "2961556046292813968", 307309581)
