-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3873970
-- Generated: 2026-09-11T12:59:35.972Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3873970) 
addappid(3873971, 1, "426d1f99b6979fafd74cccbfcf4d62638edfa295a3deaccffdbf15a58039d77f") 
setManifestid(3873971, "5501892602980122793", 44356895856)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)
addappid(4132390) 
addappid(4132400) 
addappid(4132410) 
addappid(4132630) 