-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3892270
-- Generated: 2026-09-11T02:51:19.982Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3892270, 1, "792fb0e3dedf02f8756774da38656b5b7212250cf8e33822e6b27199b2530385") 
addappid(3892271, 1, "90695be6010d5ec2e8890f1d742357316f4d5f74a8a9d22b2ae076b184797167") 
setManifestid(3892271, "4322338465787944513", 857538992)