-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3917090
-- Generated: 2026-09-11T17:03:40.946Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3917090, 1, "340b8c96bdb509c533a9035112e7f8b80d52bc2f7715a3c9062a81e131e0bbb8") 
addappid(3917093, 1, "895ccaabbb11bef3c79056dd0b38b0af79b02c722780e801b29493ef248ea713") 
setManifestid(3917093, "8347583511572866987", 20891206416)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)
addappid(229000, 1, "3aae9271fb93da5395ffbfe338d3647de5dcfab3fc6fb901ca2ec28849b3d6bf") 
setManifestid(229000, "4622705914179893434", 242681440)