-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(3935020)
addappid(3935021, 1, "0408029333b8fb91116eedd0fcdfc3aaca556fd8695ded07acfd5d99c2dace89")
setManifestid(3935021, "6268319188864346595", 12534716242)
addappid(3935022, 1, "e2d083324d8b66c7ee9b4bed9bcd9d546c24f0fcf0c5be75e1e11af6328e9524")
setManifestid(3935022, "8088685688294279609", 12628112213)
