-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 3950130
-- Generated: 2026-09-11T05:40:53.698Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(3950130) 
addappid(3950131, 1, "f71cfc5a880cff814c30939fc3b642ed54a00dc429ce29a6333681418f9bf41f") 
setManifestid(3950131, "5008819563426202732", 182834272)
addappid(3950132, 1, "8bb76a467df4f48f36883302b0000eef3079b3ce25f0ed7ab7405ee74421061c") 
setManifestid(3950132, "6838111987978612800", 189348960)
addappid(3950133, 1, "b6fa6f55c035d857f08d60d5547b7c59dda95ea2b579ad9998247711bd706d69") 
setManifestid(3950133, "4632272472218456612", 178157392)