-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(3988440)
addappid(3988441, 1, "361b3975a313b62ee08e4f5ed48d73a532f52000eb849ee9d75471df164b7725")
setManifestid(3988441, "3713750740374454163", 1006161228)
addappid(3988442, 1, "1b79058855f966fa4d9b4fe64fbf6ca8ffd1cccae36c5f4f3acc083fcef2c480")
setManifestid(3988442, "6250017330642286313", 369119)
addappid(4703370)
addappid(4703370, 1, "a82cc583e6a22c598c7007c36a99d76eb44566cc8b310131f6efbc3d896967b7")
setManifestid(4703370, "1338451732867784955", 426352337)
