-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 4001890
-- Generated: 2026-09-11T23:29:26.165Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(4001890) 
addappid(4001891, 1, "b5c8ad37740a8db6d370a6934bf203cfaeb3343003e6277ffc96c63f4df2b7ca") 
setManifestid(4001891, "3889140805796509645", 357575152)