-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(4019450)
addappid(4019451, 1, "dcf9a037fb026f552ba9d7ed4725da60eff1adfeccdbddabdc0cae657d9be0f7")
setManifestid(4019451, "997916412346131939", 284234858)
