-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 4026480
-- Generated: 2026-09-08T17:19:53.146Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(4026480) 
addappid(4026481, 1, "88a5cd641810cebf1b7d440abb9fbcbb677a99aeb9a018cecd520109c3d01d3a") 
setManifestid(4026481, "3584145531411538289", 4266763392)