-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 4055380
-- Generated: 2026-09-11T10:40:39.835Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(4055380, 1, "1413874e8afb00c37463990868f9cfb47ea876020a63d11fd02de3f8d941e939") 
addappid(4055381, 1, "c9d66eb676ab6239bc5e1dd5c5f5d57ecd66c7f72930b3958dffde1e9a6abc4a") 
setManifestid(4055381, "8108381897049202753", 87577632)
addappid(4055382, 1, "ce71523e1994ec2cc7471adab6bcf85fde819fa99c76736288bb72aa3a586e7d") 
setManifestid(4055382, "4552476307892501571", 87755568)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)