-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 4165520
-- Generated: 2026-09-09T07:29:33.666Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(4165520, 0, "b637276d6fdf995d8187d132818d2f754c01a1e7e1239d49ff4260a36238daf1")