-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(4177790)
addappid(4177791, 1, "a61bf9eeb924a34c6d14c489525dabe4a3febd1f05208d375ca2fe6dc85efac8")
setManifestid(4177791, "6619578180523604278", 2538813960)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853")
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8")
setManifestid(228990, "1829726630299308803", 102931551)
