-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 4210580
-- Generated: 2026-09-10T17:23:23.840Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(4210580) 
addappid(4210581, 1, "4d8d365d9d752745424c342dfc501048bf7d161dd44021273f535f66ee568665") 
setManifestid(4210581, "146904851148801215", 6766807712)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)