-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(4218020)
addappid(4218022, 1, "cb84f2cdfcbe4ec8c086ccc381937d95b83541806f9b639d54a0e59cbc5117a7")
setManifestid(4218022, "5239922581831236818", 4585938363)
addappid(4218023, 1, "8be1ff746819c6308fbf330f0b8932b38a80dec22ba00283f5b52edbb79b1160")
setManifestid(4218023, "4056041737935264727", 4585938363)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853")
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8")
setManifestid(228990, "1829726630299308803", 102931551)
