-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(4307420, 1, "0e96ddea44ed20788bb75a80fe6d4b3cb1ee296ce0473cdd58837861a98b370b")
addappid(4307421, 1, "6161040f989d6d6f58d4fadb8f4c461626a461a48cc9d3cbe64bc0551e3b1c0b")
setManifestid(4307421, "7034363444228987199", 7532479310)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358")
setManifestid(228988, "6645201662696499616", 29212173)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853")
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8")
setManifestid(228990, "1829726630299308803", 102931551)
