-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(4314620)
addappid(4314621, 1, "5ca2cefbd30eaa316a2fa2e4dd4c3b8fd94f6ca2fb3b02ca8d98b1713389d892")
setManifestid(4314621, "6402337261396777747", 209245960)
addappid(4314622, 1, "8d3c9ea07b8576c78cb7a783c67b3af8eb6c4d12bc1328ee7ccd213a8cd50856")
setManifestid(4314622, "2773734370376625368", 1984494668)
