-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 449680
-- Generated: 2026-09-10T19:27:40.727Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(449680) 
addappid(449681, 1, "30e511a8656ee9cdc64243952cf8f2b4440a4b991f13b2d27cd2b2237373b8e9") 
setManifestid(449681, "2020047313074209663", 86148016)

addappid(459240, 1, "b083191d959ab47ba276bb83b19b635106e13ee880e470916fff283ce2a2c6eb") 
setManifestid(459240, "1107380366985816892", 63494736)