-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(4530360, 1, "8bf0b8ae7d10740f59ce98d4845ce0a53ac197a1798a6a7154e2116c1574f771")
addappid(4530361, 1, "2c62b0881ff79cdcc172e45e5a013bbd82faa17450bb818abc63bdf0ec414b25")
setManifestid(4530361, "6828643379665666472", 25770654)
addappid(4530362, 1, "c9f2c2a9b5651c8cbe42808bdbf3d368865649b5879f83a316d75a59ff66559c")
setManifestid(4530362, "396321740992737223", 7239382)
addappid(4530363, 1, "f6c364dfa8089e0ff2a890f7adf34f6b5dba50369d5dca64d0f33f27d049f67b")
setManifestid(4530363, "5772522316344915040", 12607344)
