-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 4547970
-- Generated: 2026-09-11T22:53:47.936Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(4547970, 1, "00966a4916b37ab78438ca9e3dfd2349456731aaab870e4fd3dc1d4c60c15e19") 
addappid(4547971, 1, "d240ac24d211a2b5d94d4952b1aaf4efb56a2e90ef4a82785b2214b4aa00f447") 
setManifestid(4547971, "3597796611205913687", 5104763632)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)