-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 516750
-- Generated: 2026-09-08T10:18:23.723Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(516750, 1, "3932c6a48e426a86484b73d8bf4db22bb80e0f2ddc4bc18d56d1b867f1ec36e4") 
addappid(516751, 1, "47b5c22aa9f52cb8b5d2fe2d9db70ed709bbc88a4ba4cf24bfab8f594141ff72") 
setManifestid(516751, "7688087324231130953", 358757488)

addappid(228986, 1, "51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") 
setManifestid(228986, "8782296191957114623", 23045488)