-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 521890
-- Generated: 2026-09-12T03:37:28.213Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(521890, 1, "a435c6dd7fc5ad1c4fda215293efd2efd71f9c63e48e9eb0c96b9de022379587") 
addappid(521895, 1, "dfdc4fe90929b42105c21652ff271204a22e73f3e8dc82bb776c33551a460cf6") 
setManifestid(521895, "872403870045558848", 1747447280)

addappid(228986, 1, "51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") 
setManifestid(228986, "8782296191957114623", 23045488)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)