-- ────────────────────────────────────────────────────────────
--  Generated by GameGen
--  https://gamegen.lol
-- ────────────────────────────────────────────────────────────
addappid(61010, 1, "6af7fd7228e17c43fcf8e18f104839f6c602f34e2a2e9f06b8f9616547026f26")
addappid(61011, 1, "73ec6cb76ee55387d8ae8b33ff2b19cb3b254aed9fada6b4d66211f4c62d5b1b")
setManifestid(61011, "6919185064897761278", 7299384470)
addappid(61012, 1, "c403c1a5bc4a1a5cae9b00c6f1bdd053548db4b188f97602fd70f2ac5839d4b3")
setManifestid(61012, "1381060722851357031", 295849699)
addappid(61013, 1, "dba41af38cde7121ee4053deac477ae3ba598f1403fe3a33282d873fe38479ba")
setManifestid(61013, "3702958902715114814", 312876624)
