-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 655500
-- Generated: 2026-09-11T12:17:51.683Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(655500, 1, "42979d3d8092021906239056b53c7484c10de5b4d349ee34c791505f0f8a571a") 
addappid(655501, 1, "96ac0578416aaa4357ba79df34030dda52225e35475c7106ef2edd8aeccf345b") 
setManifestid(655501, "2142506844654146601", 2180175504)