-- Generated by centric._. (https://c3ntr1c.xyz/) for App ID 4489930
-- Generated: 2026-09-10T00:17:15.857Z
-- https://c3ntr1c.xyz/
-- Check README.txt for more information
-- Source used: depotbox


addappid(4489930) 
addappid(4489931, 1, "c6871211a6900f42f729755d89005f541d0c6a9eb1efd63c432417ced6e330e4") 
setManifestid(4489931, "6342295986500042226", 940002704)

addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") 
setManifestid(228989, "5753583882400741046", 25108528)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") 
setManifestid(228990, "1829726630299308803", 100658080)
addappid(229020, 1, "efca2304d92ac2bb7ebca174e6e5015fb0daf45d7db8ecfc1db6eaccdc7b27d9") 
setManifestid(229020, "5799761707845834510", 591984)